/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_niagenesismetadata_free: (a: number, b: number) => void;
export const __wbg_niaissuance_free: (a: number, b: number) => void;
export const __wbg_niatransition_free: (a: number, b: number) => void;
export const __wbg_sparkutkproofjs_free: (a: number, b: number) => void;
export const buildNiaTransition: (a: number, b: number, c: number, d: bigint, e: number, f: number, g: number) => [number, number, number];
export const buildNiaTransitionFromPrev: (a: number, b: number, c: number, d: number, e: number, f: bigint, g: number, h: number, i: number) => [number, number, number];
export const buildNiaTransitionMultiOutput: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const buildNiaTransitionMultiOutputFromPrev: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number];
export const deriveOutputXonly: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const deriveUTweaked: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const deriveVerifyingKey: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const issueNiaContract: (a: number, b: number, c: number, d: number, e: bigint, f: number, g: number, h: number, i: bigint) => [number, number, number];
export const niaGenesisMetadata: (a: number, b: number) => [number, number, number];
export const niaTransitionOutputs: (a: number, b: number) => [number, number, number, number];
export const niagenesismetadata_contractId: (a: number) => [number, number];
export const niagenesismetadata_name: (a: number) => [number, number];
export const niagenesismetadata_supply: (a: number) => [number, number];
export const niagenesismetadata_ticker: (a: number) => [number, number];
export const niaissuance_consignmentHex: (a: number) => [number, number];
export const niaissuance_contractId: (a: number) => [number, number];
export const niatransition_commitIdHex: (a: number) => [number, number];
export const niatransition_transitionHex: (a: number) => [number, number];
export const sparkutkproofjs_decode: (a: number, b: number) => [number, number, number];
export const sparkutkproofjs_encode: (a: number) => [number, number, number, number];
export const sparkutkproofjs_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const sparkutkproofjs_operator: (a: number) => [number, number];
export const sparkutkproofjs_uBase: (a: number) => [number, number];
export const validateNiaConsignment: (a: number, b: number) => [number, number, number, number];
export const validateNiaTransition: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const validateNiaTransitionFromPrev: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
